name: Run make test 

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  

       # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        # subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        scope: subscription
        template: ./main.bicep
        parameters: observe_customer=${{ secrets.OBSERVE_CUSTOMER }} observe_token=${{ secrets.OBSERVE_TOKEN}} observe_domain=${{ secrets.OBSERVE_DOMAIN}} objectId=${{ secrets.AZURE_OBJECT_ID }} applicationId=${{ secrets.AZURE_APPLICATION_ID }} clientSecretValue=${{ secrets.AZURE_CLIENT_SECRET }} enterpriseAppObjectId=${{secrets.AZURE_ENTERPRISE_APP_OBJECT_ID }}
        deploymentName: ${{ vars.DEPLOYMENT_NAME }}
        region: WestUS
        debug: true
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        failOnStdErr: false 
